# Generated by Django 3.2.18 on 2023-06-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_patient_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Pincode',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='petient',
            name='Pincode',
            field=models.PositiveIntegerField(),
        ),
    ]
