# Generated by Django 3.2.18 on 2023-06-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_patient_app', '0002_auto_20230615_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='CheckBox',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='petient',
            name='CheckBox',
            field=models.BooleanField(default=False),
        ),
    ]
