# Generated by Django 3.2.18 on 2023-06-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_patient_app', '0003_auto_20230615_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Pincode',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='petient',
            name='Pincode',
            field=models.CharField(max_length=10),
        ),
    ]
