# Generated by Django 3.2.18 on 2023-06-15 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_patient_app', '0005_auto_20230615_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='Profile_Pic',
        ),
    ]
