# Generated by Django 3.2.18 on 2023-06-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_patient_app', '0006_remove_doctor_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='Profile_Pic',
            field=models.ImageField(default=None, null=True, upload_to='profile_pic_doc'),
        ),
    ]
