# Generated by Django 3.2.18 on 2023-06-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_patient_app', '0008_auto_20230616_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(choices=[('MentalHealth', 'MentalHealth'), ('HeartDiasese', 'HeartDisease'), ('Covid19', 'Covid19'), ('Immunization', 'Immunization')], max_length=100)),
            ],
        ),
    ]
