# Generated by Django 3.2.18 on 2023-06-19 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_patient_app', '0009_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(choices=[('MentalHealth', 'MentalHealth'), ('HeartDiasese', 'HeartDisease'), ('Covid19', 'Covid19'), ('Immunization', 'Immunization')], max_length=100)),
                ('post_content', models.TextField(null=True)),
                ('post_image', models.ImageField(null=True, upload_to='Posts')),
                ('post_created', models.DateTimeField(auto_now_add=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Posts', to='doctor_patient_app.doctor')),
            ],
        ),
    ]
