# Generated by Django 3.2.18 on 2023-06-20 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_patient_app', '0010_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='Summury',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='Title',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
